### PR TITLE
Fancy gui

### PR DESCRIPTION
**Pull request by lad1337**
new gui ... just a test and a few things / infos are missing
more of a question if i should continue this path

if so, you might want to wait till i think its done

xdm

### CODE REVIEW

**Comment by groenlid** [comment]
It can never be too fancy lad :+1:
Been working on some migrations-scripts etc for the sites that you requested, so they should be availiable soon.

They will most likely look something like this:

``` md
{
id: 47,
source_id: 6671,
site_id: 1,
site_name: "aniDB",
link: "http://anidb.net/perl-bin/animedb.pl?show=anime&aid=6671"
}
```

Is more information required for XEM?

**Comment by lad1337** [comment]
> It can never be too fancy lad 
> okay cool :D

the data looks perfect.
will e.g. aniDB always have the site_id 1 ?

that plenty of info for XEM :)
i was also thinking of adding uranime to XEM ... but i guess its most of the time in sync with anidb just for the id mapping would you want / like that ?

**Comment by groenlid** [comment]
Have at it boss.. :+1: http://groenlid.no-ip.org/api/animedetails/1

**Comment by lad1337** [comment]
just a small update
screen shot 2014-01-10 at 23 57 42

first: pagination
second: this contains data from two providers !!
uranime and trakt.tv

the season number and season episode number are from trakt everything else is from uranime

the issue is i had to change a little bit in XDM core
specifically the "XDMID" which is an identifier of the node in the data tree to match up new and old nodes
it is now calculated based on the _tag_ if the current provider
this means that the getIdentifier method of the Element defined in the MTM has to take the _tag_

old:

``` python
    def getIdentifier(self):
        return self.getField('id')
```

new:

``` python
    def getIdentifier(self, tag=None):
        return self.getField('id', tag)
```

i needed to add the _tag_ to be able to cross match the nodes during the updates

i'll continue my work

ps no i will not leave the season number thing in the gui thats just for testing
pps none of this is uploaded yet but will be soon

**Comment by lad1337** [comment]
the last changes might need the newest development version
screen shot 2014-01-11 at 19 17 03

**Comment by groenlid** [comment]
Looks good @lad1337. Let me know when I can pull the changes and contribute :+1: 

What do you think about these suggestions?
- [ ] Add visible links to anime on sites: anidb, thetvdb, themoviedb, myanimelist
- [ ] Add back anime description and other meta information, while still keeping the new design.
- [ ] Add "number of episodes to show per page" to pagination bar.

**Comment by lad1337** [comment]
> Add visible links to anime on sites: anidb, thetvdb, themoviedb, myanimelist

sure i would add them below the config button

> Add back anime description and other meta information, while still keeping the new design.

what i didnt show is that the synonyms are available in a tooltip thing when you hover the title
i could simply add the overview and and other inrmation in there 
i simply didnt know where to add the overview since its most of the time quite a long text

> Add "number of episodes to show per page" to pagination bar.

would a config in the settings be okay ? default to 15 with any number you want

**Comment by groenlid** [comment]
> what i didnt show is that the synonyms are available in a tooltip thing when you hover the title
> i could simply add the overview and and other inrmation in there
> i simply didnt know where to add the overview since its most of the time quite a long text

I agree it would be nice to have the synonyms in a popup so the're not in the way since it's not in most cases the information for the user wants to see. We could however add an information/exclamation-icon beside the title to indicate that the user can hover/click to get more information about the anime there.

Another placement for the description/overview could be over the episodes as it were before since that's the room with the most horizontal space. We could also truncate it with some javascript-magic if there is the need. 
But I agree that the episode-list should be front-and-center and not cluttered with other information that is second grade for the user so if the overview does not fit nicely in over the episode-list-box, we should probably place it somewhere else. 

> would a config in the settings be okay ? default to 15 with any number you want

Sounds nice @lad1337  :+1: 

It's been a while since I last used jquery.datatables. Does it still write everything to the dom and just toggles the css display tag?
Will probably not be a problem anyway since we're not working with big datasets, but could be something to think about if mobile support is in the backlog.

**Comment by lad1337** [comment]
are you gonna do the pending changes ? or can / should i continue ... then again i can just continue on my fork

**Comment by groenlid** [comment]
Be my guest lad. The anime page are starting to look good :+1: 
I've reverted the pull request and will wait until the dependencies have been merged into xdm/main branch.

Let me know if you need any help :+1:

**Comment by lad1337** [comment]
external links
screen shot 2014-01-14 at 23 01 19

flipping over to info with the info button
screen shot 2014-01-14 at 23 03 39

screen shot 2014-01-14 at 23 01 32

not so pretty but a lot of room for data
screen shot 2014-01-14 at 23 01 07

will commit and push just now

**Comment by lad1337** [comment]
pushed should i open the pull request again !? its the same branch

**Comment by groenlid** [comment]
Please do :-)

lad1337 notifications@github.com wrote:

> pushed should i open the pull request again !? its the same branch 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/groenlid/xdm-anime-plugin-repo/pull/9#issuecomment-32314328

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by seertenedos** [comment]
Looks great lad. I stopped work on my anidb info plugin but once we have the eid as well I have a media addition plugin for scanning and moving existing collections that I am working on. With all the ui stuff you have done and groenlid's api this will be the best anime downloaded around by far

**Pull request merged**
